// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAC9BJureyiU21LYRr5PSJgV0L-G8ZB2F8',
    appId: '1:868692366549:web:823449591d92ac3af8fe5c',
    messagingSenderId: '868692366549',
    projectId: 'evently-7f833',
    authDomain: 'evently-7f833.firebaseapp.com',
    storageBucket: 'evently-7f833.firebasestorage.app',
    measurementId: 'G-WHL4MHQNFD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATxLLyWklZq73SeQEYsdnapO-pWMsClxI',
    appId: '1:868692366549:android:c972946826781607f8fe5c',
    messagingSenderId: '868692366549',
    projectId: 'evently-7f833',
    storageBucket: 'evently-7f833.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhRkEH2t-36t8EdNb_1mAiDvEvDWnmOy8',
    appId: '1:868692366549:ios:8640f8ab56ac0894f8fe5c',
    messagingSenderId: '868692366549',
    projectId: 'evently-7f833',
    storageBucket: 'evently-7f833.firebasestorage.app',
    iosBundleId: 'com.example.evently',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhRkEH2t-36t8EdNb_1mAiDvEvDWnmOy8',
    appId: '1:868692366549:ios:8640f8ab56ac0894f8fe5c',
    messagingSenderId: '868692366549',
    projectId: 'evently-7f833',
    storageBucket: 'evently-7f833.firebasestorage.app',
    iosBundleId: 'com.example.evently',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAC9BJureyiU21LYRr5PSJgV0L-G8ZB2F8',
    appId: '1:868692366549:web:a9dbf53c37434490f8fe5c',
    messagingSenderId: '868692366549',
    projectId: 'evently-7f833',
    authDomain: 'evently-7f833.firebaseapp.com',
    storageBucket: 'evently-7f833.firebasestorage.app',
    measurementId: 'G-DVK204THKB',
  );
}
